#!/bin/bash

function get_instance_id () {
  aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=${HOST_NAME}" \
    --query "Reservations[].Instances[].InstanceId" \
    --output text
}

function get_instance_id_with_state () {
  aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=${HOST_NAME}" "Name=instance-state-name,Values=${INSTANCE_STATE_NAME}" \
    --query "Reservations[].Instances[].InstanceId" \
    --output text
}

function start_ec2 () {
  aws ec2 start-instances \
    --instance-ids $INSTANCE_ID > /dev/null 2>&1
}

function stop_ec2 () {
  aws ec2 stop-instances \
    --instance-ids $INSTANCE_ID > /dev/null 2>&1
}

function get_ec2 () {
  aws ec2 describe-instances \
    --instance-ids $INSTANCE_ID \
    --query "Reservations[].Instances[].[InstanceId,InstanceType,LaunchTime,PrivateIpAddress,State.Name]" \
    --output table
}

function disable_delete_protection () {
  aws ec2 modify-instance-attribute \
    --instance-id $INSTANCE_ID \
    --no-disable-api-termination > /dev/null 2>&1
}

function delete_ec2 () {
  aws ec2 terminate-instances \
    --instance-ids $INSTANCE_ID > /dev/null 2>&1
}
